### ISSUE TITLE
SodaCore - Incorrect Snowflake config example for environment variables

### ISSUE THREAD

**Issue by jasonicarter** [sodadata/docs#226]
In the [Connect to Snowflake](https://docs.soda.io/soda-core/configure.html#connect-to-snowflake) docs it's mentioned to use `env_var(SNOWFLAKE_PASSWORD)`. This is incorrect and you'll received an error such as:

```shell
Could not connect to data source [...]: Encountered a problem while trying to connect to snowflake: 250001 (08001): 
Failed to connect to DB: [...].snowflakecomputing.com:443. Incorrect username or password was specified.
```
You should actually use `${SNOWFLAKE_PASSWORD}` such as:

```yaml
data_source my_ds_alias:
  type: snowflake
  connection:
    username: ${SNOWFLAKE_USER}
    password: ${SNOWFLAKE_PASSWORD}
    account: ${SNOWFLAKE_ACCOUNT}
    ...
```
