### ISSUE TITLE
metric_group should be metric_groups

### ISSUE THREAD

**Issue by vijaykiran** [sodadata/docs#6]
on https://docs.soda.io/soda-sql/documentation/sql_metrics.html

```yaml
columns:
  commission:
     metric_group: validity
     valid_format: number_percentage
     tests:
     – invalid_count == 0
```

should be 
```yaml
columns:
  commission:
     metric_groups: 
       - validity
     valid_format: number_percentage
     tests:
       – invalid_count == 0
```
